FROM wordpress:php7.4-fpm-alpine

RUN echo @testing http://nl.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories && \
    echo /etc/apk/respositories && \
    apk update && \
    apk add rsync

WORKDIR /tmp/project
COPY ./ /tmp/project

RUN chown -R www-data:www-data /var/www/html/
CMD rsync -avr /tmp/project/ /var/www/html/; php-fpm
