version: '3.7'

networks:
  default:

volumes:
  blog_volume:
  testblog-mysql-data:
    external: true

services:
  db:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}_db
    restart: always
    env_file: ../.env
    environment:
      MYSQL_DATABASE: wordpress
    volumes:
      - testblog-mysql-data:/var/lib/mysql
    ports:
      - 3346:3306
    command: '--default-authentication-plugin=mysql_native_password'

  wordpress:
    depends_on:
      - db
    build:
      context: ../
      dockerfile: ./docker/local/Dockerfile_fpm
    container_name: ${PROJECT_NAME}_wordpress
    restart: always
    env_file: ../.env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - &data-app blog_volume:/app
      - ../wp-content:/app/wp-content
      - ../bin:/app/bin
      - ./local/config/fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./local/config/fpm/php.ini:/usr/local/etc/php/php.ini

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.16.0-alpine
    container_name: ${PROJECT_NAME}_webserver
    restart: always
    ports:
      - 28631:80
    volumes:
      - *data-app
      - ../wp-content:/app/wp-content
      - ./local/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./local/config/nginx/site.conf:/etc/nginx/site.conf
