version: '3.7'

networks:
  default:

volumes:
  wp_volume:
  hhblog-mysql-data:
    external: true

services:
  db:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}_db
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: wordpress
    volumes:
      - hhblog-mysql-data:/var/lib/mysql
    ports:
      - 3336:3306

  wordpress:
    depends_on:
      - db
    image: wordpress:php7.4-fpm-alpine
#    build:
#      context: ../
#      dockerfile: ./docker/local/Dockerfile_fpm
    container_name: ${PROJECT_NAME}_wordpress
    restart: always
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - &data-app wp_volume:/var/www/html
  #      - ../wp-content:/var/www/html/wp-content
  #      - ../wp-config.php:/var/www/html/wp-config.php

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.16.0-alpine
    container_name: ${PROJECT_NAME}_webserver
    restart: always
    ports:
      - 28631:80
    volumes:
      - ./local/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./local/config/nginx/site.conf:/etc/nginx/site.conf
      - *data-app
