FROM nginx:1.16.0-alpine

RUN apk update && apk add --no-cache nginx-module-image-filter

COPY config/nginx/nginx.conf /etc/nginx/nginx.conf
COPY config/nginx/site.conf /etc/nginx/site.conf

#CMD /bin/sh "exec nginx -g 'daemon off;'"
