- hosts: localhost
  tasks:
    - name: docker build
      raw: docker-compose -f ../docker/docker-compose.prod.yml build

    - name: docker login
      raw: docker login -u test -p {{lookup('env','registrypassword')}} registry.handh.ru

    - name: docker push
      raw: docker-compose -f ../docker/docker-compose.prod.yml push

- hosts: prod
  tasks:
    - name: copy new docker-compose file
      copy:
        src: ../docker/docker-compose.prod.yml
        dest: /var/www/hhblog/docker-compose.prod.yml
    - name: docker-compose deploy
      shell: |
        export VERSION={{lookup('env','VERSION')}}
        export COMPOSE_INTERACTIVE_NO_CLI=1
        export PROJECT_NAME={{lookup('env','PROJECT_NAME')}}
        docker login -u test -p {{lookup('env','registrypassword')}} registry.handh.ru
        docker volume create --name code-$VERSION
        env $(cat .env | grep ^[A-Z] | xargs) docker stack deploy --prune --with-registry-auth -c docker-compose.prod.yml HHBLOG
        sleep 30
      args:
        chdir: /var/www/hhblog
