- hosts: localhost
  tasks:
    - name: Set vars
      set_fact:
        dockerFile: 'docker-compose.prod.yml'
        appDir: '/home/ubuntu/www/sites/wp-admin'
        stackName: 'WP_ADMIN'
    - name: docker build
      raw: docker-compose -f ../docker/{{ dockerFile }} build

    - name: docker login
      raw: docker login -u test -p {{lookup('env','registrypassword')}} registry.handh.ru

    - name: docker push
      raw: docker-compose -f ../docker/{{ dockerFile }} push

- hosts: prod
  tasks:
    - name: copy new docker-compose file
      copy:
        src: ../docker/{{ hostvars['localhost']['dockerFile'] }}
        dest: "{{ hostvars['localhost']['appDir'] }}/{{ hostvars['localhost']['dockerFile'] }}"
    - name: Deploy
      shell: |
        export VERSION={{lookup('env','VERSION')}}
        export COMPOSE_INTERACTIVE_NO_CLI=1
        export PROJECT_NAME={{lookup('env','PROJECT_NAME')}}
        mkdir -p wp-content logs
        docker login -u test -p {{lookup('env','registrypassword')}} registry.handh.ru
        docker volume create --name code-$VERSION
        export $(cat .env | xargs)
        docker stack deploy --with-registry-auth -c {{ hostvars['localhost']['dockerFile'] }} {{ hostvars['localhost']['stackName'] }}
      args:
        chdir: "{{ hostvars['localhost']['appDir'] }}"
