- hosts: localhost
  tasks:
  - name: docker build
    raw: docker-compose -f ../docker/docker-compose.dev.yml build
    #register: docker_compose_build

  - name: docker login
    raw: docker login -u test -p {{lookup('env','registrypassword')}} registry.handh.ru

  - name: docker push
    raw: docker-compose -f ../docker/docker-compose.dev.yml push

  #- debug:  var=docker_compose_build.stdout_lines

- hosts: dev
  tasks:
  - name: Set vars
    set_fact:
      appDir: '/var/www/hhblog'
  - name: Check compose file exists.
    stat:
      path: "{{ appDir }}/docker-compose.dev.yml"
    register: p
  - name: save old compose file
    shell: mv docker-compose.dev.yml docker-compose.dev-prev.yml
    when: p.stat.exists
    args:
      chdir: "{{ appDir }}"
  - name: copy new docker-compose file
    copy:
      src: ../docker/docker-compose.dev.yml
      dest: "{{ appDir }}/docker-compose.dev.yml"
  - name: docker-compose pull and down and up
    shell: |
      export VERSION={{lookup('env','VERSION')}}
      export PROJECT_NAME={{lookup('env','PROJECT_NAME')}}
      docker login -u test -p {{lookup('env','registrypassword')}} registry.handh.ru
      mkdir -p common dev local prod release wp-content
      chmod -R 777 wp-content
      docker-compose -f docker-compose.dev.yml pull
      [ -f docker-compose.dev-prev.yml ] && docker-compose -p hhblog -f docker-compose.dev-prev.yml down -v
      docker-compose -p hhblog -f docker-compose.dev.yml up -d
    args:
      chdir: "{{ appDir }}"
